### ISSUE TITLE
(1.19.4) Ticking Entity Crash when approaching Village/Villager with 'Enable villager Brain Console Debug' = YES (Default)

### ISSUE THREAD

**Issue by Tursiops-G** [gitsh01/libertyvillagers#104]
UPDATE: Setting  'Enable Villager Brain Console Debug' to **NO** prevents the crash. (It's Set to YES by Default at install).

(Tried with Minimum configuration/New World to eliminate possible Mod Conflict).

Crashlog:
---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-04-15 11:40:34
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "java.lang.StackTraceElement.getFileName()" is null
	at net.minecraft.class_4095.handler$znh000$libertyvillagers$setMemory(class_4095.java:694)
	at net.minecraft.class_4095.method_24535(class_4095.java)
	at net.minecraft.class_4095.method_18879(class_4095.java:231)
	at net.minecraft.class_7906.method_47249(class_7906.java:30)
	at net.minecraft.class_4289.method_46955(class_4289.java:32)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at net.minecraft.class_4289.method_46954(class_4289.java:32)
	at net.minecraft.class_7898$1.trigger(class_7898.java:53)
	at net.minecraft.class_7894.method_18922(class_7894.java:20)
	at net.minecraft.class_4103$class_4216$1.method_46930(class_4103.java:118)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at net.minecraft.class_4103$class_4216$1.method_19559(class_4103.java:119)
	at net.minecraft.class_4103.method_18922(class_4103.java:61)
	at net.minecraft.class_4095.method_18891(class_4095.java:533)
	at net.minecraft.class_4095.method_19542(class_4095.java:492)
	at net.minecraft.class_1646.method_5958(class_1646.java:278)
	at net.minecraft.class_1308.method_6023(class_1308.java:782)
	at net.minecraft.class_1309.method_6007(class_1309.java:2654)
	at net.minecraft.class_1308.method_6007(class_1308.java:544)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1309.method_5773(class_1309.java:2400)
	at net.minecraft.class_1308.method_5773(class_1308.java:344)
	at net.minecraft.class_1646.method_5773(class_1646.java:319)
	at net.minecraft.class_3218.method_18762(class_3218.java:722)
	at net.minecraft.class_1937.method_18472(class_1937.java:488)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_4095.handler$znh000$libertyvillagers$setMemory(class_4095.java:694)
	at net.minecraft.class_4095.method_24535(class_4095.java)
	at net.minecraft.class_4095.method_18879(class_4095.java:231)
	at net.minecraft.class_7906.method_47249(class_7906.java:30)
	at net.minecraft.class_4289.method_46955(class_4289.java:32)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at net.minecraft.class_4289.method_46954(class_4289.java:32)
	at net.minecraft.class_7898$1.trigger(class_7898.java:53)
	at net.minecraft.class_7894.method_18922(class_7894.java:20)
	at net.minecraft.class_4103$class_4216$1.method_46930(class_4103.java:118)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at net.minecraft.class_4103$class_4216$1.method_19559(class_4103.java:119)
	at net.minecraft.class_4103.method_18922(class_4103.java:61)
	at net.minecraft.class_4095.method_18891(class_4095.java:533)
	at net.minecraft.class_4095.method_19542(class_4095.java:492)
	at net.minecraft.class_1646.method_5958(class_1646.java:278)
	at net.minecraft.class_1308.method_6023(class_1308.java:782)
	at net.minecraft.class_1309.method_6007(class_1309.java:2654)
	at net.minecraft.class_1308.method_6007(class_1308.java:544)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1309.method_5773(class_1309.java:2400)
	at net.minecraft.class_1308.method_5773(class_1308.java:344)
	at net.minecraft.class_1646.method_5773(class_1646.java:319)
	at net.minecraft.class_3218.method_18762(class_3218.java:722)
	at net.minecraft.class_1937.method_18472(class_1937.java:488)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: minecraft:villager (net.minecraft.class_1646)
	Entity ID: 171
	Entity Name: Unemployed
	Entity's Exact location: 273.93, 77.56, 196.37
	Entity's Block location: World: (273,77,196), Section: (at 1,13,4 in 17,4,12; chunk contains blocks 272,-64,192 to 287,319,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.05, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:488)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Unknown Source)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Tursiops_G'/145, l='ServerLevel[LV Test World]', x=155.50, y=80.50, z=155.50]]
	Chunk stats: 2966
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2239 game time, 0 day time
	Level name: LV Test World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 6711110752 bytes (6400 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3129
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 20441.19
	Virtual memory used (MB): 17332.85
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 367.08
	JVM Flags: 9 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8192m -Xmx8192m
	Fabric Mods: 
		architectury: Architectury 8.1.79
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.78.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.26+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.5+e719b857f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.43+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.53+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.8+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.7+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.4+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.26+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.30+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.38+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.0+a6f3ccfaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.40+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.2+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.7+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.3+a383ab97f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.4+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.0+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.37+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.40+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.0+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.1+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.44+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.19+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.0+d51205dbf4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabricloader: Fabric Loader 0.14.19
		jade: Jade 10.0.0
		java: OpenJDK 64-Bit Server VM 17
		libertyvillagers: Liberty's Villagers 1.0.13+fabric+1.19.4
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
				packet_tweaker: Packet Tweaker 0.3.1+23w06a
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.1.0-rc.4
		roughlyenoughitems: Roughly Enough Items 11.0.597
			error_notifier: Error Notifier 1.0.9
		xaerominimap: Xaero's Minimap 23.3.3
		xaeroworldmap: Xaero's World Map 1.29.5
	Server Running: true
	Player Count: 1 / 8; [class_3222['Tursiops_G'/145, l='ServerLevel[LV Test World]', x=155.50, y=80.50, z=155.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19.4

**Comment by Tursiops-G** [comment]
Fixed in release 1.0.14 
Thanks!  :-)
