### ISSUE TITLE
Game doesn't open on forge

### ISSUE THREAD

**Issue by vitorabdias** [gitsh01/libertyvillagers#112]
Install Architectury and Liberty Villagers on forge 1.18.2 recommended version and you'll get this error while trying to load the game.
Am i missing some dependencies?

[16:30:06] [pool-3-thread-1/ERROR]: Could not find parent me/shedaniel/autoconfig/serializer/PartitioningSerializer$GlobalData for class com/gitsh01/libertyvillagers/config/BaseConfig in classloader cpw.mods.modlauncher.TransformingClassLoader@625a4ff on thread Thread[pool-3-thread-1,5,main]
[16:30:06] [pool-3-thread-1/ERROR]: An error occurred building event handler
java.lang.ClassNotFoundException: me.shedaniel.autoconfig.serializer.PartitioningSerializer$GlobalData
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.gitsh01.libertyvillagers.LibertyVillagersMod.<clinit>(LibertyVillagersMod.java:23) ~[libertyvillagers-2.0.0+forge+1.18.2.jar%2362!/:?]
	at net.minecraft.world.entity.ai.village.poi.PoiType.modify$zbj000$modifySearchDistance(PoiType.java:518) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?]
	at net.minecraft.world.entity.ai.village.poi.PoiType.<clinit>(PoiType.java:44) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?]
	at net.minecraft.world.entity.npc.VillagerProfession.<clinit>(VillagerProfession.java:16) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?]
	at net.minecraft.core.Registry.m_205941_(Registry.java:237) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?]
	at net.minecraft.core.Registry.lambda$internalRegister$55(Registry.java:433) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?]
	at net.minecraft.core.Registry.lambda$static$71(Registry.java:635) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:634) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:138) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by gitsh01** [comment]
Yes you also need cloth-config.

**Comment by gitsh01** [comment]
Thanks for the report, I've updated the descriptions on curseforge and modrinth state that both cloth config and architectury are required, server-translations and mod menu are optional fabric dependencies.
