### ISSUE TITLE
Crashes on server Fabric 1.20.2

### ISSUE THREAD

**Issue by Purple1222119** [gitsh01/libertyvillagers#117]
When trying to start the server, Minecraft crashes and gives the following:
`[main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.2-loader.0.14.24-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.gitsh01.libertyvillagers.LibertyVillagersMod.<clinit>(LibertyVillagersMod.java:24) ~[libertyvillagers-2.0.0+fabric+1.20.2.jar:?]
	at net.minecraft.class_7477.modify$bad000$libertyvillagers$modifySearchDistance(class_7477.java:520) ~[server-intermediary.jar:?]
	at net.minecraft.class_7477.method_43992(class_7477.java:93) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47485(class_7923.java:219) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47482(class_7923.java:234) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_7923.method_47487(class_7923.java:232) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.redirect$zmb000$fabric-registry-sync-v0$initialize(class_2966.java:565) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.gitsh01.libertyvillagers.LibertyVillagersMod.<clinit>(LibertyVillagersMod.java:24) ~[libertyvillagers-2.0.0+fabric+1.20.2.jar:?]
	at net.minecraft.class_7477.modify$bad000$libertyvillagers$modifySearchDistance(class_7477.java:520) ~[server-intermediary.jar:?]
	at net.minecraft.class_7477.method_43992(class_7477.java:93) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47485(class_7923.java:219) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.method_47482(class_7923.java:234) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_7923.method_47487(class_7923.java:232) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.redirect$zmb000$fabric-registry-sync-v0$initialize(class_2966.java:565) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	... 4 more`
	
The mods I currently have installed:
![mc mods](https://github.com/gitsh01/libertyvillagers/assets/137657974/e15ad9da-5a82-4ef6-bd4a-86c3084e0792)

**Comment by Purple1222119** [comment]
Added "Cloth Config API" to my server and now the server is running properly!
